### ISSUE TITLE
3.0-351 high CPU/ ConcurrentModificationException

### ISSUE THREAD

**Issue by cwiech** [RIPE-NCC/rpki-validator-3#65]
I am trying scale testing with this version, currently running 7 cpu's a 100%  (load average 9) at steady state (not updating clients and the validator is not updating). Unlike 3.0-333 where it seems to eventually toss and error and return to a normal CPU load, this code is stays at 100% forever.

It did have this error:

$ 2019-01-15 20:35:43.787 ERROR 8332 --- [pool-1-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.

java.util.ConcurrentModificationException: null
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1558) ~[na:1.8.0_191]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_191]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_191]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_191]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_191]
	at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:479) ~[na:1.8.0_191]
	at java.util.stream.ReferencePipeline.min(ReferencePipeline.java:520) ~[na:1.8.0_191]
	at net.ripe.rpki.rtr.domain.RtrClients.getLowestSerialNumber(RtrClients.java:72) ~[classes!/:3.0-SNAPSHOT]
	at net.ripe.rpki.rtr.RtrServer.expireOldDeltas(RtrServer.java:116) ~[classes!/:3.0-SNAPSHOT]
	at sun.reflect.GeneratedMethodAccessor59.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.0.11.RELEASE.jar!/:5.0.11.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.0.11.RELEASE.jar!/:5.0.11.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_191]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]

**Comment by lolepezy** [comment]
We are on investigating the issue.

**Comment by lolepezy** [comment]
The problem should be fixed in the latest build (377). Could you please it?

**Comment by cwiech** [comment]
Still seeing similar CPU issues. With 200 clients the load average is about ~9 all the time... even when the code is not performing any updates etc. (not packets on 8282 etc.).
